module.exports = {
    FB_LOGIN: "FB_LOGIN",
    FB_LOGIN_SUCCESS: "FB_LOGIN_SUCCESS",
    FB_LOGIN_FAILURE: "FB_LOGIN_FAILURE",

    INDEXING_FB: "INDEXING_FB",
    ALREADY_INDEXED: "ALREADY_INDEXED",
    INDEXING_FB_SUCCESS: "INDEXING_FB_SUCCESS",
    INDEXING_FB_FAILURE: "INDEXING_FB_FAILURE",

    LOADING_ICE_BUCKET_MAP: "LOADING_ICE_BUCKET_MAP",
    LOADING_ICE_BUCKET_MAP_SUCCESS: "LOADING_ICE_BUCKET_MAP_SUCCESS",
    LOADING_ICE_BUCKET_MAP_FAILURE: "LOADING_ICE_BUCKET_MAP_FAILURE",

    CHANGE_SURVEY_RESPONSE_VALUE: "CHANGE_SURVEY_RESPONSE_VALUE",
    SUBMIT_SURVEY_RESPONSE: "SUBMIT_SURVEY_RESPONSE",
    SUBMIT_SURVEY_RESPONSE_SUCCESS: "SUBMIT_SURVEY_RESPONSE_SUCCESS",
    SUBMIT_SURVEY_RESPONSE_FAILURE: "SUBMIT_SURVEY_RESPONSE_FAILURE",

    START_GRAPH_PLAYER: "START_GRAPH_PLAYER",
    PAUSE_GRAPH_PLAYER: "PAUSE_GRAPH_PLAYER",
    CHANGE_TIMELINE_PERIOD: "CHANGE_TIMELINE_PERIOD",
    RESTART_GRAPH_PLAYER: "RESTART_GRAPH_PLAYER",
    UPDATE_GRAPH: "UPDATE_GRAPH"
};